container:
  image: golang:latest

task:
  name: Run "golangci-lint"
  alias: Lint
  persistent_worker:
    labels:
      name: dev-mini
  install_go_script:
    - brew install go
  install_golangci_lint_script:
    - brew install golangci-lint
  lint_script:
    - golangci-lint run -v --output.json.path golangci.json
  always:
    report_artifacts:
      path: golangci.json
      type: text/json
      format: golangci

task:
  name: Check for missing "go generate"
  alias: Lint
  check_script:
    - go generate ./...
    - git status --porcelain
    - test -z "$(git status --porcelain)"

task:
  name: Test
  persistent_worker:
    labels:
      name: dev-mini
  install_go_script:
    - brew install go
  test_script:
    - go test -v ./...

task:
  depends_on:
    - Lint
    - Test
  persistent_worker:
    labels:
      name: dev-mini
  env:
    MACOS_SIGN_P12: ENCRYPTED[!183482723ca1a95f9c4439f7a79c9d3b115472bb18c739ed1586e12d3914ccf94ade8169eeda7332fc204f8be9c27d9f!]
    MACOS_SIGN_PASSWORD: ENCRYPTED[!417423346c567f12007f42d084bff1cfee30ee14f7e8258550157679a269c70d541c9f19224224ab0293b10f2c6d4c5e!]
    MACOS_NOTARY_ISSUER_ID: ENCRYPTED[!74076906e9fa36bca3c1da1637b0759b58bb009eb1a707446896eefad3767e8dba1d0f87e71106b98cde98ac4b037a2a!]
    MACOS_NOTARY_KEY_ID: ENCRYPTED[!af9e5da1010a6b04e548ef494acc77a6e0ce176549de98f81c5b5cdd72856de09f77e51cf0849e3c4b7a2d2c22f25ca8!]
    MACOS_NOTARY_KEY: ENCRYPTED[!c70c53f3e6c163931c7cdf9d90aff8934ef21d5dd1090158688e00b94e97c68257d9cf4ae1df873e6ae0d949866aee72!]
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
    GORELEASER_KEY: ENCRYPTED[!9b80b6ef684ceaf40edd4c7af93014ee156c8aba7e6e5795f41c482729887b5c31f36b651491d790f1f668670888d9fd!]
  matrix:
    - name: Release (Dry Run)
      only_if: $CIRRUS_TAG == ''
      install_go_script:
        - brew install go
      install_goreleaser_script:
        - brew install --cask goreleaser/tap/goreleaser-pro
      release_script: goreleaser release --skip=publish --snapshot --clean --verbose
      binaries_artifacts:
        path: "dist/**"
    - name: Release
      only_if: $CIRRUS_TAG != ''
      install_go_script:
        - brew install go
      install_goreleaser_script:
        - brew install --cask goreleaser/tap/goreleaser-pro
      release_script: goreleaser
